### ISSUE TITLE
Wrong vertical axis in normal map for 2D Lights and Shadows demo

### ISSUE THREAD

**Issue by qezz** [godotengine/godot-demo-projects#1120]
**Which demo project is affected:**

2D Lights and Shadows, `lights_and_shadows`

**Description:**

Unless intended, the vertical normal map is wrong, and leads to a confusing shape of the robot

current normal map:

![image](https://github.com/user-attachments/assets/1110c463-159e-4d0c-ac23-5b5ef768c56a)

wikipedia example from https://en.wikipedia.org/wiki/Normal_mapping:

<img width="378" alt="image" src="https://github.com/user-attachments/assets/cbac0de8-804e-415a-87ac-733542e8e512">

demo:

side "reflections" are ok:

<img width="339" alt="image" src="https://github.com/user-attachments/assets/97bf1b70-2996-4b36-ad11-abdbcbc60afe">

top and bottom reflections are wrong:

<img width="236" alt="image" src="https://github.com/user-attachments/assets/45d6cf71-d7f4-40f2-b33d-c37bf650ed41">

**Comment by aaronfranke** [comment]
This is due to different conventions for the normal map. We either need to change the image, or tell Godot to interpret it differently (I forget if Godot has the ability to use both, but lots of software does).

![normalStyles](https://github.com/user-attachments/assets/0b846bfa-0d7c-49cf-ae51-435522118631)

**Comment by Calinou** [comment]
> (I forget if Godot has the ability to use both, but lots of software does).

Yes, by checking **Normal Map Invert Y** in the Import dock.
