### ISSUE TITLE
Many HTML5 projects are broken and should be removed

### ISSUE THREAD

**Issue by BrianBHuynh** [godotengine/godot-demo-projects#1125]
**Which demo project is affected:**
https://godotengine.github.io/godot-demo-projects/

**OS/device including version:**
HTML5

**Issue description:**
Many of the demos that I've checked seem to be broken or no longer performing the way they are supposed to, so I went through and compiled a list of demos which are not performing correctly on chrome. https://godotengine.github.io/godot-demo-projects/

https://godotengine.github.io/godot-demo-projects/misc/2.5d/ character doesn't move 
https://godotengine.github.io/godot-demo-projects/2d/isometric/ doesn't start
https://godotengine.github.io/godot-demo-projects/2d/navigation/ doesn't seem to do anything? 
https://godotengine.github.io/godot-demo-projects/2d/physics_tests/ some test broken
https://godotengine.github.io/godot-demo-projects/2d/polygons_lines/ doesn't start
https://godotengine.github.io/godot-demo-projects/3d/navmesh/ doesn't do anything? 
https://godotengine.github.io/godot-demo-projects/3d/platformer/ doesn't start
https://godotengine.github.io/godot-demo-projects/audio/generator/ missing image
https://godotengine.github.io/godot-demo-projects/loading/autoload/ same as scene changer?
https://godotengine.github.io/godot-demo-projects/visual_script/pong/ doesn't seem to take inputs

**Screenshots of issue:**

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot-demo-projects/issues/786.

**Comment by ZhongGuangshen** [comment]
Could it be due to a mismatch between the project version and the engine? I'm not quite sure because some other projects' versions and engines in the HTML5 project are also not compatible, but there are no problems running them.

In https://godotengine.github.io/godot-demo-projects/ It claims that "_These projects are deployed automatically on every commit on the branch of the repository. master(godot 4. x version)_" However, when running on the web side, it shows that they are running using the godot 3.3.3 version engine
![屏幕截图 2024-10-24 195255](https://github.com/user-attachments/assets/d1b72797-d3e6-45ed-9a12-243c88145689)
![屏幕截图 2024-10-24 205827](https://github.com/user-attachments/assets/92e81d2c-4aed-4735-ae3a-bb597793b63a)


I tried **_Pong with VisualScript_** and **_2.5D Demo with GDScript_** of the HTML5 project mentioned in the Issue in the Edge browser, and indeed encountered the issues of inability to input and characters being unable to move. 

Then, I tried the **_2.5D Demo with GDScript_** in the Windows Godot engine, and overall the project ran smoothly：
in **_godot 4.3 stable_**, I successfully ran the **_2.5D Demo with GDScript_** within the **_master_**, and in **_godot 3.3.3 Stable_**, I successfully ran the **_2.5D Demo with GDScript_** in the **_3.3 branch_**, both of which can be successfully run locally
![屏幕截图 2024-10-24 205303](https://github.com/user-attachments/assets/c35db592-bd48-4d28-a7d7-bf532d80283d)
in godot stable3.3.3
![屏幕截图 2024-10-24 205352](https://github.com/user-attachments/assets/f3fba08b-41c1-4783-9908-8310b8c03773)
in godot stable4.3

![屏幕截图 2024-10-24 205553](https://github.com/user-attachments/assets/1561d625-83d7-4adf-a035-9f03b38c968a)

Then I used HTML5 templates to export the corresponding HTML5 versions using 3.3.3 table and 4.3 stable respectively, and accessed the htmls through python -m http.server + http://localhost:8000. The exported HTML5 versions were successfully run in the Edge browser, and the HTML files exported from godot 3.3.3 version 4.3 version were not encountered https://godotengine.github.io/godot-demo-projects/ The issue of characters being unable to move within

![屏幕截图 2024-10-24 210747](https://github.com/user-attachments/assets/3887d36c-86a7-41b3-b922-2f0a0dd7ee7b)
HTML5 export  in godot 3.3.3 stable
![屏幕截图 2024-10-24 205752](https://github.com/user-attachments/assets/735b519d-45fb-47df-8c59-fc25888d4c8b)
HTML5 export  in godot 4.3 stable

And I am curious that is **_these projects are deployed automatically on every commit on the branch of the repository Is the statement 'master'_** accurate? The _**Pong With GDScript**_ on ** _'master'_** has been modified in version 4.2, and it is theoretically impossible to open godot in version 3.3.3. However, in HTML5 projects, the godot version is 3.3.3 and can run successfully

**Comment by Calinou** [comment]
> And I am curious that is these projects are deployed automatically on every commit on the branch of the repository Is the statement 'master' accurate?

It's still attempting to deploy them on every commit, but it's been broken for a while.
