### ISSUE TITLE
Invalid call in 2d platformer demo.

### ISSUE THREAD

**Issue by songproducer** [godotengine/godot-demo-projects#21]
The music plays but no window appears. I get the error message:

Invalid call. Nonexistent function 'move_and_slide' in base 'KinematicBody2D (player.gd)'.

**Comment by punto-** [comment]
You have an old version of the engine, that method is in git only                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: songproducerSent: Saturday, September 17, 2016 12:39 PMTo: godotengine/godot-demo-projectsReply To: godotengine/godot-demo-projectsSubject: [godotengine/godot-demo-projects] Invalid call in 2d platformer demo. (#21)The music plays but no window appears. I get the error message:

Invalid call. Nonexistent function 'move_and_slide' in base 'KinematicBody2D (player.gd)'.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/godotengine/godot-demo-projects","title":"godotengine/godot-demo-projects","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/godotengine/godot-demo-projects"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Invalid call in 2d platformer demo. (#21)"}],"action":{"name":"View Issue","url":"https://github.com/godotengine/godot-demo-projects/issues/21"}}}

**Comment by songproducer** [comment]
I'm running godot-2.1-stable

**Comment by akien-mga** [comment]
Try the 2.1 branch for 2.1-stable: https://github.com/godotengine/godot-demo-projects/tree/2.1

**Comment by songproducer** [comment]
Thanks, that worked!
