### ISSUE TITLE
[Gui in 3D demo] How I can make it work with differend size of quad ?

### ISSUE THREAD

**Issue by JacobTheHeartless** [godotengine/godot-demo-projects#294]
Gui in 3D demo works fine but if is quad size different than 2/2 I get mouse coordination issues, conversion does not work. What lines I need to change to be able to work with different size and width rectangle size (x different than y) ?

**Comment by fkrick** [comment]
Same problem on my side :(
My idea is to get the scale factor from the "Quad" Object and do some calculation things in gdscript.

But i am new in the Godot universe and a am not quit sure if that the right approch to solve/workaround this problem

**Comment by TwistedTwigleg** [comment]
I had to make a few changes to how it all works, but now I have a version that works with different sized quad meshes.

Unfortunately, I couldn't find a great way to get it to work with scaled nodes. I'm going to keep testing to see if I can get it working with scaled nodes for a bit longer before making a PR, as if I can get it working with scaled nodes then the UI should work under almost all use cases.

**Comment by GFX5000i** [comment]
I re-rewrote most of the code, mantaining the improvements in PR #299.
The biggest issues I found was the mouse drag not returning a click_position and some times not releasing the mouse click.

**Changes:**
- Made the whole block a separated scene to demonstrate it can work across multiple instances.
- Dropped the Area.input_event and did everything manually with raycasting.
- Made quad_mesh_size automatically pick the quad size, avoiding the extra setup.
- Changed from PlaneMesh to QuadMesh. Now everyting can start with 0 rotation.
- The function will keep handling input when the mouse is outside of the area to avoid orphan clicks, but stop when the click is released.
- Changed some variable and function names to make sense with the code changes.
- Added an extra code to deal with billboard mode. But is not perfect, specially with scaling and Y-billboard + camera tilting.
- Added 2 debug scenes and other 2 debug functions in the code, but they are not necessary for the code to work and can be removed safely.
- Added HOW-TO.txt to explain the necessary setup to replicate the demo.

For as far I have tested, these changes seems to allow any kind of transformation with the base and quad nodes, including the use of animations to them.

I attached the code to this post since I'm new to Godot and some changes might not be in the engine's best practices.
I'm also not 100% confident with Github's workflow on pull requests.
[gui_in_3d.zip](https://github.com/godotengine/godot-demo-projects/files/2836640/gui_in_3d.zip)

**Comment by TwistedTwigleg** [comment]
Great! I'll try to take a look at it sometime soon, probably this weekend, just to double check everything. Not that I'm worried I will find anything, but an extra pair of eyes always helps.

I think you have the pull request workflow done correctly, but to be honest I'm not a git expert and have a tendency to accidentally mess things up, so... yeah.

It is cool that you found a way to get around the mouse drag issue, because despite my best efforts I was unsuccessful at finding any sort of workable solution. It looks like you fixed a lot of issues I was having with the original demo, which is really cool!

Thanks for making the changes @GFX5000i! I'll try to take a look at them soon.
