### ISSUE TITLE
Explicitly state the license in the demo projects files?

### ISSUE THREAD

**Issue by Sslaxx** [godotengine/godot-demo-projects#314]
Whilst the README.md file makes it clear that the projects are licensed under the terms of the MIT license, this is not explicitly stated (as it is, for example, in the Godot Engine source proper) in the .gd files for the projects.

**Comment by aaronfranke** [comment]
See also: https://github.com/godotengine/godot-demo-projects/issues/241

**Comment by aaronfranke** [comment]
I'm going to close this because I don't think it would be useful to have a license in every single file. It would be a lot of extra content in each file for little to no benefit.

The license should already be clear simply from the `LICENSE.md` file at the root of the repository, which is pointed to in the `README.md`, and also GitHub lists the repo as "⚖️ MIT".

I think the only time it's relevant to list licenses in the projects would be if certain assets are under a different license for some reason, otherwise everything should be assumed to be MIT licensed and owned by Juan/Ariel and "Godot engine contributors".
