### ISSUE TITLE
GUI in 3D - When panel is upside down the input coordinates are wrong

### ISSUE THREAD

**Issue by tomglenn** [godotengine/godot-demo-projects#342]
When you first install the GUI in 3D demo and run it, the 3D GUI panel is upside down. When in this state, if you try to interact with the UI elements you will notice that it's almost as if your mouse coordinates are flipped, so to interact with the button at the bottom you have to put your mouse to the top of the panel etc.

Flipping the panel around the right way in scene view and everything works fine.

**Comment by Schroedi** [comment]
What version of Godot did you use? I just tried it in a more or less recent 3.2-dev build and did not have the problem.

**Comment by lukacat10** [comment]
3.1.1 stable

Also, after flipping, it does work fine for the most part (button is clickable only on the button, and the textbox is editable only within its boundaries as well), but the slider control is not accurate:
When sliding, the slider goes further then the mouse instead of snapping to the mouse's position (looks like the slider is moving not with the mouse coordinates, but with a multiply of it).

**Comment by aaronfranke** [comment]
This demo was rewritten in #299, and it works really well now. So I'll this.
