### ISSUE TITLE
Outdated versions in Godot Asset Library

### ISSUE THREAD

**Issue by t-karcher** [godotengine/godot-demo-projects#352]
Most of the demo projects from this repository offered in the Godot Asset Library were last updated in January 2018, so many updates and fixes (including the update to V3.1) are not available in the Asset Library yet:

https://godotengine.org/asset-library/asset?sort=updated&user=Godot+Engine

Let me know if there's anything I can do to update those assets, but I assume this can only be done by the repository owners.

**Comment by akien-mga** [comment]
CC @bojidar-bg

**Comment by bojidar-bg** [comment]
I updated all demos that had been submitted in the past.
There are some new demos though:
```
./2d/dodge_the_creeps/
./2d/finite_state_machine/
./2d/grid_based_movement/
./2d/navigation_astar/
./2d/role_playing_game/
./2d/sdf_font/
./2d/sprite_shaders/
./3d/ik/
./3d/truck_town/
./audio/bpm_sync/
./audio/generator/
./audio/mic_record/
./audio/spectrum/
./misc/android_iap/
./misc/background_load/
./misc/opensimplexnoise/
./mono/DodgeTheCreepsCS/
./networking/webrtc_minimal/
./networking/webrtc_signaling/
./networking/websocket_chat/
./networking/websocket_minimal/
./networking/websocket_multiplayer/
```

I would get to them at a later time, since they require more work (screenshots, descriptions, making sure my mass-upload script won't mess up)

Note that I could not get bpm_sync and mic_record working on 3.1.1, so I did not upload them in the GitHub release holding the assets.

**Comment by t-karcher** [comment]
Thanks! Since my original question (to update the already existing, outdated assets) is solved, I'll close this issue. Feel free to open a new one for the new demos (if needed).
