### ISSUE TITLE
IK demo is out of date

### ISSUE THREAD

**Issue by fire** [godotengine/godot-demo-projects#375]
**Which demo project is affected:**

https://github.com/godotengine/godot-demo-projects/tree/master/3d/ik

**OS/device including version:**
Windows 10 N/a

**Issue description:**
IK is not using the skeleton ik system.

https://godotengine.org/article/skeleton-inverse-kinematic

As shown here:

https://downloads.tuxfamily.org/godotengine/demos/inverse_kinematics.zip

**Comment by TwistedTwigleg** [comment]
I'd argue the IK demo is not out of date, but rather it shows how to create an IK system in GDScript, which is where the value of the demo is. There are very few examples of how to work with the Skeleton node in Godot using GDScript, and even less examples of a working IK system (in Godot or in other game engines).

Also, the IK demo was added *before* the SkeletonIK node, and (likely) helped influence the design of the SkeletonIK node given they share much of the same pros, cons, and quirks.

That said, I'm not against it being removed/updated to use the SkeletonIK node instead. You'll have to remove the `ik_look_at` examples though, since there is no SkeletonIK equivalent.

**Comment by aaronfranke** [comment]
Well, it will need to be updated to something after 3.2 is out, because it's very broken in 3.2.

**Comment by TwistedTwigleg** [comment]
I'll download the project later today and see if I can quickly figure out what is going on.

**Comment by GeorgeS2019** [comment]
@TwistedTwigleg Just want to feedback that [the pull request ](https://github.com/godotengine/godot-demo-projects/pull/382)is a major contribution to the godot community. Thank you!

**Comment by GeorgeS2019** [comment]
I also want to add here the [tutorial here ](https://www.youtube.com/watch?v=Q4o_7_Rh510)is a good start for how to use Godot SkeletonIK.

It will be great to demo how to combine the Godot SkeletonIK to create **procedural animation** using GDScript or C#

**Comment by TheMoye** [comment]
Oops sory,
I just read the headline, "out of date" didn't sound like "doesn't work." 😜
