### ISSUE TITLE
Single demo project for engine features

### ISSUE THREAD

**Issue by winipcfg** [godotengine/godot-demo-projects#39]
Right now each demo has its own separate project.
Developer need to close and open projects one by one to check engine features.

It should be better if there is a single entry point for demo instead. 
i.e. create a single project with MainScene that links up to different demo Scene. 

With this change, it also help to demonstrate scene management and scene transition technique.

**Comment by pwab** [comment]
I like the idea but...

> Developer need to close and open projects one by one to check engine features.

I think a video trailer like discussed in godotengine/godot#5917 would be a better fit for this purpose.

> i.e. create a single project with MainScene that links up to different demo Scene.

As said I like the idea but I'm not sure if this would be feasible. My two main concerns:

1. Instancing the MainScene into a view container (think of a gameboy screen) shouldn't be that hard but how to handle demos which rely on the scene trees root?
2. Every time a demo is changed this project has to be updated/checked or it could fail (and you don't want to link new users to a project which is not bullet proof)

> With this change, it also help to demonstrate scene management and scene transition technique.

I'm pretty sure there is already a demo for that. And a corresponding docs page. Would this be worth the effort?

**Comment by williamd1k0** [comment]
I don't like the idea of merging all demos into a single one but it would be interesting to have a demo focused on some main features.

I already have an example of a project like this because I did something similar last year to show the Godot Engine (2.1) features during a local gamedev event.

This project can be found here: https://github.com/williamd1k0/godot-pong-ex

**Comment by LikeLakers2** [comment]
I agree with this idea. The demos feel more "how to build a genre of game" rather than "look at this cool thing the engine can do!" There's no indication of what demo project utilizes what.

If each demo was focused on a single concept, I imagine the repo would be easier to maintain and also easier to understand before you even open the demo. For example, we could have one demo on the VideoPlayer functionality, one demo on built-in networking functionality, one for CSGShapes, one for mono support... you get the picture.

Of course, that doesn't mean we shouldn't throw the current demos away. Some of them are pretty good as examples of actual games, like the 2D RPG example. But I think for a demo repository, we should focus more on showing individual features, rather than bundling many together in a single demo and expecting the end user to figure out what features what.

**Comment by henriiquecampos** [comment]
I disagree, it is better to have each demo focused on a very specific feature so that they are small, simple and context agnostic. This allows developers to easily browse the project they are interested in and see a simple approach to solve a given problem.

Bundling all together will be strange since they are all disconnected from each other, some need custom settings for the `project.godot` file, which may conflict, so putting them into the same sack would be strange. It could be a single project that makes uses of such features, but it would be very *ad hoc* since it would need to put them into a context that intersects all those features.

Imo is better to have each as an independent project.

**Comment by aaronfranke** [comment]
This is the same as #423. For a number of reasons, this won't happen.
