### ISSUE TITLE
gui_in_3d is flipped in Godot 3.2.2

### ISSUE THREAD

**Issue by sadovsf** [godotengine/godot-demo-projects#518]
**Which demo project is affected:**
gui_in_3d

**OS/device including version:**
MacOS 10.15.6

**Issue description:**
When this demo is run UI rendering is flipped around. There is possibility in viewport options to v-flip viewport which fixes it being upside down but even then UI is mirrored. Inputs work as if UI is rendered correctly so i assume there is some issue with rendering to viewport. I was not able to find how to mirror it so it is correct.

**Screenshots of issue:**
![image](https://user-images.githubusercontent.com/2211533/92567326-d36a1500-f27d-11ea-9dbe-b30bbaf48b65.png)

**Comment by Calinou** [comment]
It seems like https://github.com/godotengine/godot-demo-projects/issues/342 reappeared. cc @aaronfranke

**Comment by aaronfranke** [comment]
The problem is that you are running an old version of the demo. The bug does not exist anymore, it has already been fixed.

The current version of the demo has a bigger panel, it looks like this:

![](https://raw.githubusercontent.com/godotengine/godot-demo-projects/master/viewport/gui_in_3d/screenshots/gui.png)

**Comment by sadovsf** [comment]
Oh, i'am really sorry i have no idea how a managed to download old version. I did re-download this repo and for sure demo works.
