### ISSUE TITLE
Create a demo that shows how to configure 3D graphics settings with a GUI

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot-demo-projects#520]
We could probably benefit from a demo that shows how to change and save various graphics settings (MSAA, effects, light shadows, …) with a GUI. People could then copy its scenes and scripts to other projects that need a graphics settings menu.

The GUI itself would only have minimal theming, since the main point of the demo is to show the logic required to create a configuration utility. Settings would be saved and loaded using the ConfigFile class.

The demo would likely use GLES3, but we can detect the current renderer and hide incompatible features from the menu automatically if using the GLES2 renderer. This will make it easier to reuse.

I'm willing to work on this demo if desired.

**Comment by aaronfranke** [comment]
Why isn't the TPS demo sufficient for this? :)

![Screenshot from 2020-09-15 15-04-50](https://user-images.githubusercontent.com/1646875/93253441-dc1e8780-f764-11ea-8e61-343aa9e551a9.png)

**Comment by Calinou** [comment]
@aaronfranke I forgot this was in the TPS demo. Maybe we should still have a more minimal demo where it's easier to copy-paste the scenes and scripts?

PS: We could add a few more settings to the TPS demo, such as for glow quality.

**Comment by aaronfranke** [comment]
I don't think it's worth having every single thing in its own standalone demo, if we had that then we would have a thousand demos and it would be very difficult to maintain.

In this particular case, I especially think this shouldn't be its own standalone demo, since if you change graphics settings you need some kind of visuals to test them out, and the TPS demo already has a high quality environment with lighting and GI in it.

If you would like to add a few things to the TPS demo, go ahead. I'll close this issue in the meantime.

**Comment by Calinou** [comment]
For future reference, this was implemented in https://github.com/godotengine/godot-demo-projects/pull/719.
