### ISSUE TITLE
Dodge the Creeps: Godot UI shows CollisionObject2D instead PhysicsBody2D for Mob scene

### ISSUE THREAD

**Issue by jhaand** [godotengine/godot-demo-projects#665]
**Which demo project is affected:**
Demo project: Dodge the creeps!

**OS/device including version:**
Debian Linux/ Godot 3.4. stable.official

**Issue description:**
Expected: The Tutorial "Your first game" mentions to change the mask on PhysicsBody2D for the Mob.
Observed: Only the heading "CollisionObject2D" shows a Layer and Mask to change. No heading found called PhysicsBody2D found. 
Furthermore: I'm unable to see a collision between the Player and Mob scene. If I trigger a "hit" signal it's game over. But the game continues when the Player gets hit by a Mob. 

**Screenshots of issue:**
![Godot_Collision_Object](https://user-images.githubusercontent.com/14841399/144122605-1507adca-d808-4dfc-9456-1b29fe22dc3d.png)

Attached

**Comment by aaronfranke** [comment]
@jhaand Thanks for reporting this, but this is a documentation issue instead of a demo issue, and actually it's one that has already been fixed with the updated tutorial, it just hasn't been pushed to the "stable" branch of the docs yet.

Here is the updated tutorial: https://docs.godotengine.org/en/latest/getting_started/first_2d_game/index.html
