### ISSUE TITLE
using get_node() as standart for beginner level demos

### ISSUE THREAD

**Issue by hubbyist** [godotengine/godot-demo-projects#72]
I have a pleading about get_node() usage for demo projects.

While reading PR #53 it seems to me that "$" notation is preferred over get_node() while reviewing new demo projects. 

I think that `get_node()` for **beginner** level demos is a better choice as standard. `$` notation is more cryptic for beginners by nature. I am using Godot at high school level for students with zero coding experience. Using get_node() needs no further explanation and makes tutoring more easy. If standart for beginner level demos would be "always use get_node()", I will be very grateful. Although new demos seems to be not using get_node too often, I think this is still important to decide.

I what I mean as beginner level demos are projects mentioned in "Step by step" section and for most of the 2d folder. Ithink 3d folder is for more determined learners so $ notation will not be the main problem there.

WDYT?

**Comment by ElfEars** [comment]
eh, honestly I think it would be better to just leave a note at the start of all beginner scripts stating that $ is synonymous with get_node()

**Comment by hubbyist** [comment]
It may work as well and may be better for consistency. But does not solve `$` being cryptic problem which is my main concern.

**Comment by TwistedTwigleg** [comment]
Personally I think $ notation is rather cryptic and while it does make code more compact I’m personally not convinced on how useful it actually is (nor what problem it’s intended to fix)

I personally think we should avoid using $ in the demos to avoid confusing new users.

**Comment by vnen** [comment]
I understand that the `$` is quite cryptic for beginners, but I don't think that demos are in their concept a way to learn. They are in fact a way to showcase the engine features, and a reference for people already familiarized with Godot. So in general the should do it "the Godot way", which is using the shorthand notation.

For entry-level tutorials—and projects that might accompany them—I'm okay with using `get_node()` and preferring more explicit notations.

**Comment by TwistedTwigleg** [comment]
(NOTE: this is just my option on the matter. I have nothing against the developers nor anyone who likes `$`)

I think there are several problems with the `$` in general. The first and foremost being that it’s cryptic for beginners to the engine (regardless of how much experience they may have in programming in other languages and/or other game engines). I don’t necessarily think there is anything wrong with advance/cryptic features, but I think it’s best to keep them away from beginner demos in order to be more approachable.

I don’t know what `$` is even for. Is it for condensing code? Are there performance gains with using `$` over using `get_node`? It is just a preference?, Did someone complain about `get_node`? Regardless of why it was added, I don’t think it’s very clear what it’s ideal usecase is. Does anyone mind explaining why it was added? I’m not against it’s inclusion, but I really just have no idea why it was added 😅 .

Another (minor) issue with having `$` in all of the demo projects is that it enforces a condensed coding style. Some people find condensed code hard to read and it’s not necessarly a style everyone likes. That’s fine but I personally think condensed code isn’t neccessarily better than explicit code.

____

As far as the demo projects go, I was under the impression that the demos were for beginning users. I understand the demos are also being used as a feature showcase and that’s why most of them are short projects showing one single feature.

If the demos are for more familiarized Godot users and/or for reference, then shouldn’t we focus on making more advance demos? Like the platform changes suggested in issue #50 should (probably) be added so we have reference on how to orbit a camera around an object and/or changing the camera to a different position on demand.

I personally think we should have another repository for advance demos. In this repository we can have `$` (if whoever made the demo wants to use it), make more complete demos (For example a platformer with multiple levels, orbiting camera, a life system, power ups, etc) and better show what Godot can do. I have no problem helping with said repository.

Or we could just add a ‘advance’ folder and we could put all of the advance demos there instead.


Finally, regardless on what is decided I think we should have a guideline for contributing, or at least a basic style guide. I think it’ll make contributing easier for future users and will help solve issues like this one.

____

Anyway, **that’s just my two cents on the matter**. I’m not trying to step on toes or anything, I’m just stating what I think on the matter 😃.

**Comment by vnen** [comment]
Just as a note, a `get_node()` shorthand was asked for quite a few people and most of them used jQuery as an example. Hence the use of the `$` character, since it's the most obvious for those with jQuery in mind. `get_node()` is used quite a lot, so it makes sense to have a simpler notation. That's what it is: a shorthand, there's no other difference from the longer notation.

> If the demos are for more familiarized Godot users and/or for reference, then shouldn’t we focus on making more advance demos?

Not really, because the focus are the main features. It's hard to showcase one thing if you have many other things going on.

**Comment by TwistedTwigleg** [comment]
> Just as a note, a get_node() shorthand was asked for quite a few people and most of them used jQuery as an example. Hence the use of the $ character, since it's the most obvious for those with jQuery in mind.

Good to know! That makes sense, and also explains why it's just `$`, which I couldn't wrap my head around. Thank you for explaining :+1:

**Comment by TwistedTwigleg** [comment]
I noticed in commit #92 that all of the 2D demos now use the `$` syntax. Is `$` now the standard for the demos?

(If so, can we at least add a note in the scripts and/or in the [GDScript style guide](http://docs.godotengine.org/en/latest/learning/scripting/gdscript/gdscript_styleguide.html)?)

**Comment by aaronfranke** [comment]
Hypothetically speaking, if I were designing Godot from scratch, I would not have included `$` since it's hardly a necessary feature and does add complexity and confusion.

However, since this feature does exist, I think it makes sense to use it. I've been updating all of the demo projects for the past month and now the usage of `$` is basically everywhere.

Perhaps beginner tutorials should use `get_node` instead of `$`, or maybe it's better for them to use `$` to get people familiar with the syntax early on, I'm not sure. One thing that may be the greatest advantage of `$` is that, as of Godot 3.2, they have a very unique color in the syntax highlighting:

![$ operator syntax highlighting example from the Dodge the Creeps demo](https://user-images.githubusercontent.com/1646875/76044779-4e4a2000-5f29-11ea-96c3-161619caa301.png)

**Comment by aaronfranke** [comment]
Closing this issue because it is not actionable as-is. My thoughts are above, but otherwise I don't see a strong consensus of what should be done. Feel free to continue the discussion.
