### ISSUE TITLE
GUI in 3D demo does not work

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot-demo-projects#84]
Current master for Godot 3.0.

It loads fine, but the GUI elements can't be interacted with, which kind of defeats the purpose of the demo.

**Comment by TwistedTwigleg** [comment]
Strange. It worked fine before on Linux...

I’ll see what I can do this weekend (or sooner if time allows)

**Comment by TwistedTwigleg** [comment]
Well, it seems this isn't a bug with the GUI in 3D demo per say, but rather it seems that godotengine/godot#12149 broke the demo (because we're passing a handled event to the Viewport).

I'm not really sure how to fix this one. We could add another function to Viewport, a force_input function that forces whatever input to be processed regardless if its been handled. Another way we could potentially get around this is to allow the ability to set a input event as unhandled (I think this could lead to major issues down the road though).

What do you guys think?

**Comment by RaXaR** [comment]
Any news on this one? I was kinda hoping to use this feature soon. Even a workaround/suggestion would be very welcome :)

**Comment by TwistedTwigleg** [comment]
Unfortunately there isn’t any known workaround that I know of. I made a PR to add a force_input function, but it was decided that further debugging was needed, so I closed it and that was the last I’ve heard on the matter.

If you’re okay with changing the source and compiling, you can use the code from the closed PR as a workaround:https://github.com/godotengine/godot/pull/13152

**Comment by RaXaR** [comment]
Awesome,  I'll take a look. Thanks for sharing.

**Comment by RaXaR** [comment]
I don't know what to do with this line since the function has changed:
https://github.com/godotengine/godot/pull/13152/files#diff-b0e269beca0e7df95d035998c40ecb64R2675
any thoughts?

**Comment by RaXaR** [comment]
Aha, I searched the preceding line and it moved all the way to the bottom of the file.  I'll continue to tinker and see what comes out. :)

**Comment by RaXaR** [comment]
Nice, it worked. In the "GUI in 3D" demo I had to change line 65 to ```viewport.force_process_input(event)``` and it did the trick.
