### ISSUE TITLE
3D Scaling in 4.0-dev not working

### ISSUE THREAD

**Issue by voylin** [godotengine/godot-demo-projects#856]
**Which demo project is affected:**
3D scaling in viewport

**OS/device including version:**
Linux Arch lts

**Issue description:**
Filtering works, however the scaling does not work at all. I've been trying to fix this demo myself as I need it for some of my personal projects but I can't find what's wrong with it. Is this still a 4.0 bug or is there something I'm missing here? Setting the size of the subviewport does not work and the size 2D override doesn't seem to be doing anything.

**Comment by Calinou** [comment]
The demo should be updated to use the built-in resolution scaling features that are new in 4.0.

**However**, the old approach should still be provided as an alternative – likely as a separate project. This is because the old approach is the only one that works when using the Compatibility (OpenGL) rendering method. It's also currently the only way to use nearest-neighbor filtering instead of bilinear filtering or FSR 1.0 (until https://github.com/godotengine/godot-proposals/issues/4697 is implemented).

**Comment by Nrosa01** [comment]
What are those built-in resolution scaling features in godot 4? I tried the scaling project because I needed to do something similar and faced the same problem

**Comment by Calinou** [comment]
> What are those built-in resolution scaling features in godot 4?

https://docs.godotengine.org/en/latest/tutorials/3d/resolution_scaling.html

**Comment by Calinou** [comment]
Fixed by https://github.com/godotengine/godot-demo-projects/pull/891 being manually merged.
