### ISSUE TITLE
Screenshots are broken on asset library due to file name/format change

### ISSUE THREAD

**Issue by GuillaumeOz** [godotengine/godot-demo-projects#895]
Hi, 

PNG is missing to this url :

https://godotengine.org/asset-library/asset/132

Error : 404 not found

**Comment by Calinou** [comment]
Demos use WebP screenshots in the `master` branch, but we should modify screenshot URLs to reflect the state of the demos in Godot 3.5 anyway. This means using the `3.5` branch instead of `master` for icon URLs.

This will require going through all official demos one by one. I've fixed RichTextLabel so far.

**Comment by InfiniteProductions** [comment]
I would like to help @Calinou, just to be sure to understand before working on this, the goal is to convert all screenshots into webp format and update all readme accordingly, right ?

Is there any preferred settings ? (compression level, lossless, etc)

**Comment by Calinou** [comment]
I resolved this issue yesterday, so this issue can now be closed.
