### ISSUE TITLE
3D Platformer

### ISSUE THREAD

**Issue by DoctorMikeReddy** [godotengine/godot-demo-projects#996]
**Which demo project is affected:**

godot-demo-projects/3D/platformer

**OS/device including version:**

Windows 10

**Issue description:**

Game hangs  with error:
Invalid set index 'parameters/state/current' (on base: 'AnimationTree') with value of type 'int'

**Screenshots of issue:**
![image](https://github.com/godotengine/godot-demo-projects/assets/1001087/0296dd89-ad16-4001-8d36-bdc0d7779a99)

**Comment by DoctorMikeReddy** [comment]
Fixed. I just had to use transition_request instead of current

**Comment by Calinou** [comment]
This is already fixed in the latest revision of the demo: https://github.com/godotengine/godot-demo-projects/blob/40ce32c5da977981139d7abedb52c9d4ec01177a/3d/platformer/player/player.gd#L174

[Demos on the asset library are only for 3.x, not for 4.x](https://github.com/godotengine/godot-demo-projects/issues/920), so make sure to grab demos from this repository in the meantime.

**Comment by DoctorMikeReddy** [comment]
I did get it from the repo
